import type {
  CarouselConfigOverrides,
  CarouselStep,
} from "@neuro-pay/carousel";

// NeuroPay's content and theme for the carousel. Everything here is an
// override on top of @neuro-pay/carousel's upstream defaults, so this file
// doubles as a readable diff: if it isn't mentioned below, it's stock.

export interface Step extends CarouselStep {
  aspect: number;
  /** Short locator shown above the row, e.g. "04 — Gateway". */
  label: string;
  /** The card's own headline. Not rendered in the overlay — see below. */
  title: string;
  /** Caption revealed in focus mode. */
  note: string;
}

// Card artwork is generated by scripts/gen-panels.mjs — edit the copy there
// and re-run `pnpm --filter @neuro-pay/web panels`.
//
// `aspect` must match the generated card or the row spacing goes wrong.
const PORTRAIT = 760 / 1000;
const LANDSCAPE = 1040 / 700;

export const STEPS: Step[] = [
  {
    src: "/p01.png",
    aspect: PORTRAIT,
    label: "NeuroPay",
    title: "Agents buy the services they need",
    note: "A catalog of paid APIs, and the gateway that settles them on BNB Chain.",
  },
  {
    src: "/p02.png",
    aspect: PORTRAIT,
    label: "01 — Catalog",
    title: "Every paid API, with a price per call",
    note: "Owners list an endpoint and set a price. Agents read the catalog without an account.",
  },
  {
    src: "/p03.png",
    aspect: PORTRAIT,
    label: "02 — Discovery",
    title: "The agent finds what it needs",
    note: "Listings rank by price, latency and uptime. Nothing has been paid yet.",
  },
  {
    src: "/p04.png",
    aspect: LANDSCAPE,
    label: "03 — Request",
    title: "It calls the endpoint, unpaid",
    note: "No key, no card, no session — the agent just asks.",
  },
  {
    src: "/p05.png",
    aspect: LANDSCAPE,
    label: "04 — Gateway",
    title: "HTTP 402 Payment Required",
    note: "The gateway answers with a price, a chain and an address. One status code is the whole handshake.",
  },
  {
    src: "/p06.png",
    aspect: PORTRAIT,
    label: "05 — Authorization",
    title: "Checked against the owner's grant",
    note: "Over the cap, the gateway refuses. The agent never holds the keys.",
  },
  {
    src: "/p07.png",
    aspect: PORTRAIT,
    label: "06 — Settlement",
    title: "Settled in USDC on BNB Chain",
    note: "The money moves before the call runs. No escrow, no invoice, no trust.",
  },
  {
    src: "/p08.png",
    aspect: LANDSCAPE,
    label: "07 — Execution",
    title: "Paid. Now the call runs",
    note: "The gateway forwards upstream and hands back the response with a receipt.",
  },
  {
    src: "/p09.png",
    aspect: PORTRAIT,
    label: "08 — Receipt",
    title: "Every call leaves proof",
    note: "Reconcile any agent's spend, on-chain, per call.",
  },
  {
    src: "/p10.png",
    aspect: PORTRAIT,
    label: "09 — Integrate",
    title: "Two lines",
    note: "402 handled, grant enforced, USDC settled. Your code just sees a response.",
  },
];

/**
 * Page background. Shared with the renderer's clear color so the gaps between
 * cards blend into the page instead of showing seams. Keep in sync with
 * `--carousel-ink` in app/globals.css.
 */
export const PAGE_BG = 0x05060a;

/** Passed to createCarousel() as `config`; merged over the package defaults. */
export const carouselConfig: CarouselConfigOverrides = {
  STEPS,
  PAGE_BG,

  CONFIG: {
    // Taller than the upstream photo carousel on purpose: these cards carry
    // body copy and monospace detail, which needs the extra on-screen size.
    // The generator's type scale is built around this number — changing it
    // means re-checking the small text on the cards.
    PANEL_H: 600,
    GAP: 28,
  },

  FOCUS: {
    // Gentler than upstream's 1.18: the cards are already 600px tall, so a
    // big focus scale runs them into the overlay text on shorter viewports.
    // The other cards dropping away carries the emphasis instead.
    centerScale: 1.06,
  },

  // Tinted BNB gold, and dialled well back. The upstream glow/ring values
  // were built against a white page; on near-black they bloom into an opaque
  // band that swallows the cards.
  LENS: {
    blueColor: "#F0B90B",
    dispersion: 7,
    glow: 0.9,
    whiteGlow: 0.05,
    blueRing: 1.1,
    ringWidth: 0.012,
    shimmerDepth: 0.1,
    rimLine: 0.32,
  },

  // Stock upstream choreography, stated explicitly because the overlay reads
  // `enabled` to decide whether to start hidden and wait for the entry.
  ENTRY: {
    enabled: true,
  },
};

/**
 * Overlay text transitions. Not part of the carousel config — the engine
 * never sees these; they only drive the React layer's fades.
 */
export const UI_ANIM = {
  duration: 0.4,
  ease: "power3.out",
  revealDuration: 1.6,
  revealEase: "power2.out",
  /** Counter follows the top text by this delay, in seconds. */
  revealStagger: 0.18,
} as const;
